version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsfinanceiro-frontend
    ports:
      - "127.0.0.1:8082:80"
    restart: unless-stopped
    networks:
      - default
      - deploy_default

networks:
  default:
  deploy_default:
    external: true
