"use server";
import { revalidatePath } from "next/cache";import { z } from "zod";import { requireFinanceContext } from "@/lib/finance/context";
export type CardState={error?:string;success?:string};
const money=z.preprocess(v=>typeof v==="string"?Number(v.replace(/\./g,"").replace(",",".")):v,z.number().finite().min(0).max(999999999));
const schema=z.object({account_id:z.string().uuid(),name:z.string().trim().min(2).max(60),brand:z.string().trim().max(30).optional(),last_four:z.string().regex(/^\d{4}$/).optional().or(z.literal("")),credit_limit:money,closing_day:z.coerce.number().int().min(1).max(31),due_day:z.coerce.number().int().min(1).max(31)});
export async function createCard(_:CardState,data:FormData):Promise<CardState>{const p=schema.safeParse(Object.fromEntries(data));if(!p.success)return{error:"Revise os dados do cartão."};const{supabase,userId,workspace}=await requireFinanceContext();const{data:account}=await supabase.from("accounts").select("id").eq("id",p.data.account_id).eq("workspace_id",workspace.id).eq("owner_id",userId).eq("active",true).maybeSingle();if(!account)return{error:"Conta do cartão inválida."};const{error}=await supabase.from("credit_cards").insert({...p.data,brand:p.data.brand||null,last_four:p.data.last_four||null,workspace_id:workspace.id,owner_id:userId});if(error)return{error:"Não foi possível adicionar o cartão. Use uma conta ainda sem cartão."};revalidatePath("/cartoes");revalidatePath("/");return{success:"Cartão adicionado."}}
export async function archiveCard(data:FormData){const id=z.string().uuid().safeParse(data.get("id"));if(!id.success)return;const{supabase,userId,workspace}=await requireFinanceContext();await supabase.from("credit_cards").update({active:false}).eq("id",id.data).eq("owner_id",userId).eq("workspace_id",workspace.id);revalidatePath("/cartoes");revalidatePath("/")}

const purchaseSchema=z.object({credit_card_id:z.string().uuid(),description:z.string().trim().min(1).max(160),total_amount:money.refine(v=>v>0),purchased_on:z.string().date(),installment_count:z.coerce.number().int().min(1).max(120),category_id:z.string().uuid().optional().or(z.literal("")),notes:z.string().trim().max(500).optional(),idempotency_key:z.string().uuid()});
export async function createPurchase(_:CardState,data:FormData):Promise<CardState>{const p=purchaseSchema.safeParse(Object.fromEntries(data));if(!p.success)return{error:"Revise os dados da compra."};const{supabase}=await requireFinanceContext();const{error}=await supabase.rpc("create_installment_purchase",{p_credit_card_id:p.data.credit_card_id,p_description:p.data.description,p_total_amount:p.data.total_amount,p_purchased_on:p.data.purchased_on,p_installment_count:p.data.installment_count,p_category_id:p.data.category_id||null,p_notes:p.data.notes||null,p_idempotency_key:p.data.idempotency_key});if(error)return{error:"Não foi possível registrar a compra."};revalidatePath(`/cartoes/${p.data.credit_card_id}`);revalidatePath("/cartoes");revalidatePath("/");return{success:"Compra e parcelas criadas."}}
const paymentSchema=z.object({invoice_id:z.string().uuid(),credit_card_id:z.string().uuid(),account_id:z.string().uuid(),paid_on:z.string().date(),idempotency_key:z.string().uuid()});
export async function payInvoice(_:CardState,data:FormData):Promise<CardState>{const p=paymentSchema.safeParse(Object.fromEntries(data));if(!p.success)return{error:"Revise os dados do pagamento."};const{supabase}=await requireFinanceContext();const{error}=await supabase.rpc("pay_credit_card_invoice",{p_invoice_id:p.data.invoice_id,p_account_id:p.data.account_id,p_paid_on:p.data.paid_on,p_idempotency_key:p.data.idempotency_key});if(error)return{error:"Não foi possível pagar esta fatura."};revalidatePath(`/cartoes/${p.data.credit_card_id}`);revalidatePath("/movimentacoes");revalidatePath("/");return{success:"Fatura paga e saldo atualizado."}}
