create extension if not exists pgcrypto;

create type public.account_type as enum ('checking','cash','savings','credit_card','investment');
create type public.transaction_type as enum ('income','expense','transfer');
create type public.transaction_status as enum ('planned','pending','paid','cancelled');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now());
create table public.workspaces (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, kind text not null default 'personal' check(kind in ('personal','family','business')), currency char(3) not null default 'BRL' check(currency='BRL'), created_at timestamptz not null default now(), unique(id,owner_id));
create table public.accounts (id uuid primary key default gen_random_uuid(), workspace_id uuid not null, owner_id uuid not null references auth.users(id) on delete cascade, name text not null, type public.account_type not null, initial_balance numeric(14,2) not null default 0, active boolean not null default true, created_at timestamptz not null default now(), unique(id,workspace_id,owner_id), foreign key(workspace_id,owner_id) references public.workspaces(id,owner_id) on delete cascade);
create table public.categories (id uuid primary key default gen_random_uuid(), workspace_id uuid not null, owner_id uuid not null references auth.users(id) on delete cascade, name text not null, kind public.transaction_type not null check(kind <> 'transfer'), color text, created_at timestamptz not null default now(), unique(id,workspace_id,owner_id), foreign key(workspace_id,owner_id) references public.workspaces(id,owner_id) on delete cascade);
create table public.transactions (id uuid primary key default gen_random_uuid(), workspace_id uuid not null, owner_id uuid not null references auth.users(id) on delete cascade, account_id uuid not null, category_id uuid, destination_account_id uuid, type public.transaction_type not null, status public.transaction_status not null default 'paid', description text not null, amount numeric(14,2) not null check(amount > 0), competence_date date not null, paid_at date, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(workspace_id,owner_id) references public.workspaces(id,owner_id) on delete cascade, foreign key(account_id,workspace_id,owner_id) references public.accounts(id,workspace_id,owner_id), foreign key(category_id,workspace_id,owner_id) references public.categories(id,workspace_id,owner_id), foreign key(destination_account_id,workspace_id,owner_id) references public.accounts(id,workspace_id,owner_id), check((type='transfer' and destination_account_id is not null and category_id is null and destination_account_id<>account_id) or (type<>'transfer' and destination_account_id is null)));
create table public.fixed_commitments (id uuid primary key default gen_random_uuid(), workspace_id uuid not null, owner_id uuid not null references auth.users(id) on delete cascade, account_id uuid, category_id uuid, description text not null, amount numeric(14,2) not null check(amount > 0), due_day smallint not null check(due_day between 1 and 31), active boolean not null default true, created_at timestamptz not null default now(), foreign key(workspace_id,owner_id) references public.workspaces(id,owner_id) on delete cascade, foreign key(account_id,workspace_id,owner_id) references public.accounts(id,workspace_id,owner_id), foreign key(category_id,workspace_id,owner_id) references public.categories(id,workspace_id,owner_id));

alter table public.profiles enable row level security;alter table public.workspaces enable row level security;alter table public.accounts enable row level security;alter table public.categories enable row level security;alter table public.transactions enable row level security;alter table public.fixed_commitments enable row level security;
create policy "profiles_own" on public.profiles for all to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy "workspaces_own" on public.workspaces for all to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy "accounts_own" on public.accounts for all to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy "categories_own" on public.categories for all to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy "transactions_own" on public.transactions for all to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy "fixed_commitments_own" on public.fixed_commitments for all to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now();return new;end;$$;
create trigger transactions_set_updated_at before update on public.transactions for each row execute function public.set_updated_at();
grant usage on schema public to authenticated;grant select,insert,update,delete on public.profiles,public.workspaces,public.accounts,public.categories,public.transactions,public.fixed_commitments to authenticated;
create index workspaces_owner_idx on public.workspaces(owner_id);create index accounts_workspace_idx on public.accounts(workspace_id,owner_id);create index categories_workspace_idx on public.categories(workspace_id,owner_id);create index transactions_workspace_date_idx on public.transactions(workspace_id,owner_id,competence_date desc);create index transactions_account_idx on public.transactions(account_id);create index transactions_category_idx on public.transactions(category_id);create index commitments_workspace_idx on public.fixed_commitments(workspace_id,owner_id);
